### ISSUE TITLE
it seems  forgot to s.nextMediasoupWorkerIdx++ in server.getMediasoupWorker()

### ISSUE THREAD

**Issue by pertgame** [jiyeyuran/mediasoup-go-demo#1]
func (s *Server) getMediasoupWorker() *mediasoup.Worker {
	worker := s.mediasoupWorkers[s.nextMediasoupWorkerIdx]

	if s.nextMediasoupWorkerIdx == len(s.mediasoupWorkers) {
		s.nextMediasoupWorkerIdx = 0
	}

	return worker
}

**Comment by jiyeyuran** [comment]
fixed, thank you.
