### ISSUE TITLE
无法启动mediasoup-go-demo

### ISSUE THREAD

**Issue by tzhang1119** [jiyeyuran/mediasoup-go-demo#2]
panic: channel timeout

goroutine 1 [running]:
main.NewServer({{0x159ba1f, 0x9}, {{0xc00002cba0, 0x7}, 0x115b, {{0xc000028228, 0x15}, {0xc000028270, 0x13}}}, {0x1, ...}})
        /Volumes/MAC_DATA/work_tv/go_path/ms_go1_svr/server/server.go:49 +0x534
main.main()
        /Volumes/MAC_DATA/work_tv/go_path/ms_go1_svr/server/main.go:41 +0x3ff

**Comment by jiyeyuran** [comment]
fixed
