### ISSUE TITLE
Triuble at start project

### ISSUE THREAD

**Issue by shark4web** [jiyeyuran/mediasoup-go-demo#3]
Installed Mediasoup V3, clone repository, run `go build` and server folder, `npm install` and `npm start` at app folder. Server has been started ON, front too.  But when try to connect - got panic message at server:

2022-09-26T15:00:32+03:00 INF Server > protoo connection request address=127.0.0.1 origin=https://satel-local.eyevox.ru:3000 peerId=4re2t7ui roomId=nh0tc0un
2022-09-26T15:00:32+03:00 ERR worker[pid:762789] > (stderr) terminate called after throwing an instance of 'std::invalid_argument'
2022-09-26T15:00:32+03:00 ERR worker[pid:762789] > (stderr)   what():  stoul
2022-09-26T15:00:32+03:00 ERR Worker > process died error="worker process died unexpectedly" code=-1 pid=762789 signal=aborted
2022-09-26T15:00:32+03:00 ERR Channel > read failed error="read |0: file already closed"
2022-09-26T15:00:32+03:00 ERR Room > create router error="InvalidStateError:Channel closed, id: 1, method: worker.createRouter"
2022-09-26T15:00:32+03:00 ERR Server > getOrCreateRoom error="InvalidStateError:Channel closed, id: 1, method: worker.createRouter"
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
2022/09/26 15:00:32 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:78)
2022-09-26T15:00:32+03:00 ERR PayloadChannel > PayloadChannel error failed error="read |0: file already closed"
2022-09-26T15:00:32+03:00 ERR Server > mediasoup Worker died, exiting in 2 seconds... error="worker process died unexpectedly"

2022/09/26 15:00:32 [Recovery] 2022/09/26 - 15:00:32 panic recovered:
GET /?roomId=nh0tc0un&peerId=4re2t7ui HTTP/1.1
Host: satel-local.eyevox.ru:4443
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: Upgrade
Origin: https://satel-local.eyevox.ru:3000
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: bIiHyv00EfYdRsEytH3lmQ==
Sec-Websocket-Protocol: protoo
Sec-Websocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36

http: connection has been hijacked
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:59 (0x83a65e)
	JSON.Render: panic(err)
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:841 (0x83c017)
	(*Context).Render: if err := r.Render(c.Writer); err != nil {
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:884 (0x83f14a)
	(*Context).JSON: c.Render(code, render.JSON{Data: obj})
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:176 (0x83f0f2)
	ErrorLoggerT.func1: c.JSON(-1, errors)
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x84049a)
	(*Context).Next: c.handlers[c.index](c)
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x840486)
	RecoveryWithWriter.func1: c.Next()
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x83f686)
	(*Context).Next: c.handlers[c.index](c)
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0x83f669)
	LoggerWithConfig.func1: c.Next()
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x83e4a4)
	(*Context).Next: c.handlers[c.index](c)
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x83e0d9)
	(*Engine).handleHTTPRequest: c.Next()
/home/oem/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x83dd73)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2947 (0x706b4b)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1991 (0x702606)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1594 (0x46c000)
	goexit: BYTE	$0x90	// NOP

[GIN] 2022/09/26 - 15:00:32 | 500 |   699.12751ms |       127.0.0.1 | GET      "/?roomId=nh0tc0un&peerId=4re2t7ui"
Error #01: InvalidStateError:Channel closed, id: 1, method: worker.createRouter

This is a Virtual  Box PC, based on Linux Mint (Ubuntu), tried 3, 4 and 6 cores for it.

**Comment by jiyeyuran** [comment]
thanks, fixed. Please upgrade this project and run `go build` in the `server` directory.
